### ISSUE TITLE
Create dedicated console text box at the bottom for serial output

### ISSUE THREAD

**Issue by gianlazz** [sameezch/OMNI-BAND#19]
Add box and newline after each line so that it auto scrolls

**Comment by gianlazz** [comment]
@sameezch Created serialTextBox feature branch for you to work on this

**Comment by sameezch** [comment]
This won't work. I'll just make a dedicated text box with raw sensor data once we get the floats working.

**Comment by sameezch** [comment]
Instead of a console I just made number boxes that will show the raw data from the sensors. This is much cleaner than a console. 

edb073617c817b0c4ac60ea752c0aa57e69c53ba
